logLevel: info

# RTSP server (publisher sẽ push tới đây)
rtsp: yes
rtspAddress: :8554

rtmp: no

# HLS global (dùng để serve .m3u8)
hls: yes
hlsAddress: :8888
hlsAlwaysRemux: yes
hlsSegmentDuration: 1s
hlsSegmentCount: 10

# Cấu hình WebRTC (WHEP/WHIP)
webrtc: yes
webrtcAddress: :8889

webrtcAllowOrigin: 'http://localhost:3002'
# -----------------------

paths:
  all:
    source: publisher
    maxReaders: 50