networks:
  violence-detection-net:
    driver: bridge

services:
  # --- Zookeeper ---
  zookeeper:
    image: bitnamilegacy/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - violence-detection-net
    restart: unless-stopped

  # --- Kafka ---
  kafka:
    build:
      context: ..
      dockerfile: docker/Dockerfile.kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - violence-detection-net
    restart: unless-stopped

  # --- MinIO ---
  minio:
    image: bitnamilegacy/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # Cổng API/Data
      - "9001:9001" # Cổng Console UI
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=mypassword
    volumes:
      - minio_data:/data 
    networks:
      - violence-detection-net
    restart: unless-stopped

  # --- MinIO Client (Tự động tạo Bucket) ---
  minio_client:
    image: bitnamilegacy/minio-client:latest
    container_name: minio_client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "sleep 10 && mc alias set minio http://minio:9000 minio mypassword && mc mb minio/inference-results && mc mb minio/checkpoint && tail -F anything"
    networks:
      - violence-detection-net

  # --- RTSP Pusher ---
  rtsp_pusher:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rtsp-pusher
    container_name: rtsp_pusher
    environment:
      RTSP_BASE: rtsp://mediamtx:8554
    volumes:
      - ../data/processed/clips_for_streaming:/app/data/processed/clips_for_streaming:ro
      - ../data/metadata:/app/data/metadata:ro
      - ../tmp/rtsp-pusher:/app/tmp
      - ../logs/rtsp-pusher:/app/logs
      - ../pids:/app/pids
    depends_on:
      - mediamtx
    networks:
      - violence-detection-net
    restart: on-failure

  # --- Mediamtx (RTSP Server) ---
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
    environment:
      RTSP_AUTH_USER: ""
      RTSP_AUTH_PASS: ""
    networks:
      - violence-detection-net
    restart: unless-stopped
    volumes:
      - ../config/mediamtx/mediamtx.yml:/mediamtx.yml

  # --- Producer ---
  producer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.producer
    container_name: producer
    depends_on:
      - kafka
      - minio
      - mediamtx # Producer cần Mediamtx để kết nối
    environment:
      # Cấu hình biến môi trường cho Producer Python
      MINIO_ENDPOINT: minio:9000
      KAFKA_BROKER: kafka:9092
    networks:
      - violence-detection-net
    volumes:
      # Mount code để dễ debug/cập nhật
      - ../scripts:/app/scripts
      - ../data:/app/data
    restart: on-failure

  # --- Inference Worker ---
  inference_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.producer
    container_name: inference_worker
    restart: always
    command: python /app/scripts/inference_worker.py
    environment:
      PYTHONUNBUFFERED: 1
      MINIO_ENDPOINT: minio:9000
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
      - producer # Đảm bảo producer đã gửi dữ liệu
    networks:
      - violence-detection-net
    volumes:
      - ../scripts:/app/scripts
      - ../data:/app/data

  spark-master:
    build:
      context: ..
      dockerfile: docker/Dockerfile.spark
    container_name: spark-master
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION: no
      SPARK_RPC_ENCRYPTION: no
      SPARK_LOCAL_CONF_DIR: /opt/bitnami/spark/conf/
      HOME: /tmp 
      SPARK_HOME: /opt/bitnami/spark
      SPARK_USER: sparkuser
    ports:
      - "8080:8080" # Spark Web UI
    networks:
      - violence-detection-net
    volumes:
      # Mount script PySpark
      - ../scripts:/opt/bitnami/spark/scripts
      - ../config/spark:/opt/bitnami/spark/conf/
    restart: always

  spark-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.spark
    container_name: spark-worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
    networks:
      - violence-detection-net
    volumes:
      - ../scripts:/opt/bitnami/spark/scripts
      - ../config/spark:/opt/bitnami/spark/conf/
    depends_on:
      - spark-master
    restart: always
    
# # ---- Hive metastore -----
  mysql:
    image: mysql:8.4.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - violence-detection-net

#   hive-metastore:
#     build:
#       context: ..
#       dockerfile: docker/Dockerfile.hive
#     container_name: hive-metastore
#     hostname: hive-metastore
#     ports:
#       - '9083:9083'
#     volumes:
#       - ../config/hive_metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
#     environment:
#       METASTORE_DB_HOSTNAME: mysql
#     depends_on:
#       - mysql
#     networks:
#       - violence-detection-net

  hive-metastore:
    build:
      context: ..
      dockerfile: docker/Dockerfile.hive
    container_name: hive-metastore
    hostname: hive-metastore
    ports:
      - "9083:9083"
    environment:
      # chọn none | init | upgrade
      - HIVE_SCHEMA_ACTION=none
      # mysql host/port (sử dụng tên service 'mysql' trong docker-compose)
      - WAIT_FOR_HOST=mysql
      - WAIT_FOR_PORT=3306
      - WAIT_TIMEOUT=120
      - HIVE_CONF_DIR=/opt/hive/conf
      - HIVE_HOME=/opt/hive
      - HIVE_SCHEMA_ACTION=init
    volumes:
      # mount hive-site.xml (bạn phải chuẩn bị file này)
      - ../config/hive_metastore/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
      # optional: mount local lib if bạn muốn override hoặc thêm jars
    depends_on:
      - mysql
    networks:
      - violence-detection-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - violence-detection-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    user: "0" # Fix permission issues in some environments
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - violence-detection-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    # Thu thập metrics từ máy chủ Docker Host
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host)($$|/)'
    restart: unless-stopped
    networks:
      - violence-detection-net
volumes:
  zookeeper_data:
  kafka_data:
  minio_data:
  mysql-data:
  grafana-storage: