version: "3.9"

networks:
  violence-detection-net:
    driver: bridge

services:
  # --- Zookeeper ---
  zookeeper:
    image: bitnamilegacy/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - violence-detection-net
    restart: unless-stopped

# --- Kafka ---
  kafka:
    build:
      context: ..
      dockerfile: docker/Dockerfile.kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092 
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - violence-detection-net
    restart: unless-stopped

  # --- MinIO ---
  minio:
    build:
      context: ..
      dockerfile: docker/Dockerfile.minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../config/minio/config.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_REGION: ap-southeast-1
    volumes:
      - minio_data:/data
    networks:
      - violence-detection-net
    restart: unless-stopped

# ...
  rtsp_pusher:
    build:
      context: .. 
      dockerfile: docker/Dockerfile.rtsp-pusher
    container_name: rtsp_pusher
    environment:
      RTSP_BASE: rtsp://mediamtx:8554
    volumes:
      - ../data/processed/clips_for_streaming:/app/data/processed/clips_for_streaming:ro
      - ../data/metadata:/app/data/metadata:ro
      - ../tmp/rtsp-pusher:/app/tmp
      - ../logs/rtsp-pusher:/app/logs
      - ../pids:/app/pids
    depends_on:
      - mediamtx
    networks:
      - violence-detection-net
    restart: on-failure

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554" # RTSP
      - "8888:8888" # HTTP/HLS
      - "8188:8188" # Web UI 
    environment:
      RTSP_AUTH_USER: ""
      RTSP_AUTH_PASS: ""
    networks:
      - violence-detection-net
    restart: unless-stopped

  producer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.producer
    container_name: producer
    # Producer chạy ngay sau khi MinIO và Kafka sẵn sàng
    depends_on:
      - kafka
      - minio
      - mediamtx # Producer cần Mediamtx để kết nối
    environment:
      # Cấu hình biến môi trường cho Producer Python
      MINIO_ENDPOINT: minio:9000
      KAFKA_BROKER: kafka:9092
    networks:
      - violence-detection-net
    volumes:
      # Mount code để dễ debug/cập nhật
      - ../scripts:/app/scripts
    restart: on-failure
volumes:
  zookeeper_data:
  kafka_data:
  minio_data:
