apiVersion: 1
datasources:
  - name: Trino_Security_DB
    type: trino
    uid: trino_security_ds
    url: http://trino-coordinator:8080
    user: admin
    access: proxy
    isDefault: false
    jsonData:
      catalog: iceberg
      schema: default
      authType: none
    editable: true